# Generated by Django 2.2.7 on 2020-01-18 00:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
