# Generated by Django 2.2.7 on 2020-01-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200114_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_totla',
            new_name='shipping_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totla',
            new_name='total',
        ),
    ]
